
apiVersion: v1
kind: Service
metadata:
  name: {{ template "elastalert.fullname" . }}
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service_ws.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    app: {{ template "elastalert.name" . }}
    release: {{ .Release.Name }}